### ISSUE TITLE
[src] Angles of the block missiles

### ISSUE THREAD

**Issue by kokekanon** [MillhioreBT/forgottenserver-downgrade#1]
Hello, I had in browser favorites, several posts from otland of with  bug c++ in 1.5, which the community could not solve

test in release "beta-test-1"

I think  have a problem in c++
with respect to the angles of the block missiles
I rule out that it is the .dat because the "block Missiles" is selected.
How make the angles of attack more restricted?

![fffhh](https://github.com/MillhioreBT/forgottenserver-downgrade/assets/114332266/b1e3b7d6-8e22-4748-a0dc-9a6bfb88ce4e)

![Screenshot_43](https://github.com/MillhioreBT/forgottenserver-downgrade/assets/114332266/90e28e71-f1f1-4a3d-8612-9be6d146627f)

![image](https://github.com/MillhioreBT/forgottenserver-downgrade/assets/114332266/3cdb94d8-7c07-44b9-b56b-e6cdb4e3bbc5)

**Comment by MillhioreBT** [comment]
It's quite rare, since Tibia RL's new line of sight was introduced this can happen
I have to find out if this really works like this in Tibia RL

**Comment by MillhioreBT** [comment]
This repository will maintain the new line of sight that is currently used in Tibia RL, [there is a PR that can solve this problem](https://github.com/otland/forgottenserver/pull/4521), and you can apply it if you need, thank you very much for reporting this issue.
