### ISSUE TITLE
Erro in compilation Windows

### ISSUE THREAD

**Issue by luanluciano93** [MillhioreBT/forgottenserver-downgrade#13]
![image](https://github.com/MillhioreBT/forgottenserver-downgrade/assets/6209529/03f4f43f-9ca6-49d0-b119-29fbd7edd4cd)

**Comment by MillhioreBT** [comment]
> ![image](https://user-images.githubusercontent.com/6209529/282328665-03f4f43f-9ca6-49d0-b119-29fbd7edd4cd.png)

I have already updated the command to install the libraries in the windows tutorial

But in your case, you only need to install sol2
you can use this command: `./vcpkg install --triplet x64-windows sol2`

**Comment by luanluciano93** [comment]
work fine, thank you
