### ISSUE TITLE
Ubuntu 22.04

### ISSUE THREAD

**Issue by MathRavz** [MillhioreBT/forgottenserver-downgrade#17]
Error to compile ubuntu 22.04

------

CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find Lua54 (missing: LUA_LIBRARIES LUA_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindLua54.cmake:61 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:53 (find_package)

**Comment by marcosCapistrano** [comment]
Install Lua54 with apt

**Comment by MillhioreBT** [comment]
The compilation instructions in the tutorial have already been updated
https://github.com/MillhioreBT/forgottenserver-downgrade/wiki/Compiling-on-Ubuntu
