### ISSUE TITLE
Exaust Problem

### ISSUE THREAD

**Issue by IsacViana** [MillhioreBT/forgottenserver-downgrade#19]
I'm having problems with Exhaustor in Scripts I want to set time to use x item or use x command and I can't because the base doesn't pull the os.time or something similar.

![image](https://github.com/MillhioreBT/forgottenserver-downgrade/assets/140405320/def30381-966e-42d8-a621-16db7652e79a)

When I put 1 it works fine, but when I put 0.x or 1.x it doesn't work.

**Comment by MillhioreBT** [comment]
In Lua 5.4, integer numbers are differentiated from float numbers, so if you don't round the number before passing it to the storage method then you will get a warning.

**Comment by IsacViana** [comment]
Isn't there a way to do 0.8s, 1.6s, and so on? @MillhioreBT

**Comment by MillhioreBT** [comment]
> Isn't there a way to do 0.8s, 1.6s, and so on? @MillhioreBT

```lua
function Player.setExhaustion(self, key, milliseconds)
    return self:setStorageValue(key, os.mtime() + milliseconds)
end

function Player.getExhaustion(self, key)
    local milliseconds = self:getStorageValue(key)
    return math.max(0, os.mtime() - milliseconds)
end

function Player.hasExhaustion(self, key) return self:getExhaustion(key) > 0 end
```

you must use milliseconds directly.
