### ISSUE TITLE
bug broadcasted ( /b )

### ISSUE THREAD

**Issue by kokekanon** [MillhioreBT/forgottenserver-downgrade#21]
<details>
<summary>solved /b | message between player</summary>

# private message between players
```lua
ERROR: ProtocolGame parse message exception (36 bytes, 10 unread, last opcode is 0xaa (170), prev opcode is 0xffffffff (-1)): unknown message mode 0
Packet has been saved to packet.log, you can use it to find what was wrong. (Protocol: 860)
```
# /b
/b asdasd
![image](https://github.com/MillhioreBT/forgottenserver-downgrade/assets/114332266/95cb74a0-a73b-488c-b95f-fa4d7fce0957)
windows 10  , 1 player online (player gm)

`targetPlayer:sendPrivateMessage(player, param, TALKTYPE_BROADCAST)`
OTcv8
```
ERROR: ProtocolGame parse message exception (36 bytes, 10 unread, last opcode is 0xaa (170), prev opcode is 0xffffffff (-1)): unknown message mode 0
Packet has been saved to packet.log, you can use it to find what was wrong. (Protocol: 860)
```
mehah
```
ERROR: ProtocolGame parse message exception (36 bytes, 10 unread, last opcode is 0xaa (170), prev opcode is 0xffffffff (-1)): unknown message mode 0
Packet has been saved to packet.log, you can use it to find what was wrong. (Protocol: 860)
```
Old client
![image](https://github.com/MillhioreBT/forgottenserver-downgrade/assets/114332266/577b7a18-bf0d-4d98-9c2e-f046d0098c66)

### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use contact.millhiorebt.com for support)
- [x] This issue is reproducible without changes to the C++ code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. command /b "hola"
2. check termial
3.

### Reproduction environment

last commits 
![image](https://github.com/MillhioreBT/forgottenserver-downgrade/assets/114332266/c8782865-019f-4f57-b454-0a0c0966efc5)
</details>

player sends a private  message to a gm (work)
gm sends a private message to a player (not work)

```lua
ERROR: ProtocolGame parse message exception (42 bytes, 10 unread, last opcode is 0xaa (170), prev opcode is 0x38 (56)): unknown message mode 0
Packet has been saved to packet.log, you can use it to find what was wrong. (Protocol: 860)
```
https://github.com/MillhioreBT/forgottenserver-downgrade/assets/114332266/e11c741d-c191-46ee-8909-6e7608aae16b

old client

https://github.com/MillhioreBT/forgottenserver-downgrade/assets/114332266/6bd321fb-c603-4b25-8135-f5113036865c

![image](https://github.com/MillhioreBT/forgottenserver-downgrade/assets/114332266/de143c8a-6971-4735-b83c-1b18b789c7a5)

**Comment by MillhioreBT** [comment]
it was already resolved
