### ISSUE TITLE
if stackpos greater than 10 then BUG end

### ISSUE THREAD

**Issue by kokekanon** [MillhioreBT/forgottenserver-downgrade#3]
Hello, I had in browser favorites, several posts from otland of with  bug c++ in 1.5, which the community could not solve

test in release "beta-test-1"

if 10 people stack in a specific position (tested in normal_zone)
the client presents the following bug

For some reason if there are many people stack in a sqm gives debug
example:
+10 people stack on a ladder

![image](https://github.com/MillhioreBT/forgottenserver-downgrade/assets/114332266/0eb9561a-c2df-47d7-8d04-6a819afe55e4)

+10 player mc or random player in a server in production 
stack in ladder
![image](https://github.com/MillhioreBT/forgottenserver-downgrade/assets/114332266/3967dbfa-dcc4-4a5d-b5de-041534a11792)

It causes an error in the client in the case of OTC this happens
(relogin is fixed, but if you login and up ladder bug again xd )

![123123](https://github.com/MillhioreBT/forgottenserver-downgrade/assets/114332266/a65ef478-eb71-4a08-acca-7d5c76301d1c)

Terminal OTC:
```
ERROR: too many things, pos=306 43 6, stackpos=11
at:
    [C++]: ?setTileDescription@ProtocolGame@@QEAAHAEBV?$shared_ptr@VInputMessage@@@std@@VPosition@@@Z
ERROR: unable to remove creature
at:
    [C++]: ?parseCreatureMove@ProtocolGame@@AEAAXAEBV?$shared_ptr@VInputMessage@@@std@@@Z
ERROR: too many things, pos=306 43 6, stackpos=11


```

Old client Debug windows
```
Debug Assertion 8.0 Map.cpp 519
Tue Feb 14 20:14:13 2023
Windows Version: 6.2 build 9200 on 2
Graphic Engine: DirectX9 (2)
Last Packet Types: 100 162 142 162 143 160 180 160 140 108
Last Packet: 230 021 170 000 000 000 000 000 000 000 000 005 010 000 157 000
Player Position: [306,43,6]
Player Name: MaXXXXX
Player.cpp 358: exception occurred, reason:
Network.cpp 980: exception occurred (ErrorCode = 0), reason:
Control.cpp 1309: exception occurred (Type = 100), reason:
Communication.cpp 1532: exception occurred (PlayerX = 306) (PlayerY = 43), reason:
Communication.cpp 1509: exception occurred (xmin = 0) (ymin = 0), reason:
Communication.cpp 1488: exception occurred (Type = 98) (OldType = 98), reason:
Map.cpp 524: exception occurred, reason:
Map.cpp 519: too many objects on map point, reason:
ObjectCount: 10
Comment:```

**Comment by MillhioreBT** [comment]
Thanks for reporting it, I'll fix it.

**Comment by kokekanon** [comment]
I realized something

if there is +10 player in stack,  affects how the player 11 raises.
example
in the video if I go up from East to West  :white_check_mark:
SE to NO :white_check_mark:
but from south to north :x: bug ahaha wtf 

https://github.com/MillhioreBT/forgottenserver-downgrade/assets/114332266/4c349378-ca99-4a1b-ac09-8dfd370196ec

**Comment by MillhioreBT** [comment]
> I realized something
> 
> if there is +10 player in stack (upstairs), affects how the player 11 raises. example in the video if I go up from East to West ✅ SE to NW ✅ but from south to north ❌ bug ahaha wtf West to East ❌ bug
> 
>  Secuencia.01_2.mp4 
> In the previous comment, I realized in the first video, the player goes up from **south to north** BUG and in the second video, the player goes from **W to E**. BUG
> 
> but in this type of ladder works
> 
> ![image](https://user-images.githubusercontent.com/114332266/240662612-54b83085-dd76-4f82-a0b4-e80b76a37719.png)

I think it's already resolved.
let me know if it works for you.
[beta-4](https://github.com/MillhioreBT/forgottenserver-downgrade/releases/tag/beta-test-4)

**Comment by kokekanon** [comment]
> > I realized something
> > if there is +10 player in stack (upstairs), affects how the player 11 raises. example in the video if I go up from East to West ✅ SE to NW ✅ but from south to north ❌ bug ahaha wtf West to East ❌ bug
> > Secuencia.01_2.mp4
> > In the previous comment, I realized in the first video, the player goes up from **south to north** BUG and in the second video, the player goes from **W to E**. BUG
> > but in this type of ladder works
> > ![image](https://user-images.githubusercontent.com/114332266/240662612-54b83085-dd76-4f82-a0b4-e80b76a37719.png)
> 
> I think it's already resolved. let me know if it works for you. [beta-4](https://github.com/MillhioreBT/forgottenserver-downgrade/releases/tag/beta-test-4)

I confirm that works in otcv8 and client CipSoft

thank you

**Comment by kokekanon** [comment]
![image](https://github.com/MillhioreBT/forgottenserver-downgrade/assets/114332266/b964d286-790d-4264-8e83-3571d8c940a1)
sorry but
now there is a problem going down the stairs haha

stack +10 player on ladder
go down the 1 player ladder


nothing happens to the person who goes down
but to those who are there. bug



https://github.com/MillhioreBT/forgottenserver-downgrade/assets/114332266/44034aed-e3a5-4bcc-859b-1bf1df4bb7fc



```

ERROR: no thing at pos:92 127 6, stackpos:6
at:
    [C++]: ?getMappedThing@ProtocolGame@@QAE?AV?$shared_object_ptr@VThing@@@stdext@@ABV?$shared_object_ptr@VInputMessage@@@3@@Z
ERROR: no thing
at:
    [C++]: ?parseTileTransformThing@ProtocolGame@@AAEXABV?$shared_object_ptr@VInputMessage@@@stdext@@@Z

```

**Comment by MillhioreBT** [comment]
> ![image](https://user-images.githubusercontent.com/114332266/241122085-b964d286-790d-4264-8e83-3571d8c940a1.png) sorry but now there is a problem going down the stairs haha
> 
> stack +10 player on ladder go down the 1 player ladder
> 
> nothing happens to the person who goes down but to those who are there. bug
> 
>  2023-05-26.00-54-27_1.mp4 
> ```
> 
> ERROR: no thing at pos:92 127 6, stackpos:6
> at:
>     [C++]: ?getMappedThing@ProtocolGame@@QAE?AV?$shared_object_ptr@VThing@@@stdext@@ABV?$shared_object_ptr@VInputMessage@@@3@@Z
> ERROR: no thing
> at:
>     [C++]: ?parseTileTransformThing@ProtocolGame@@AAEXABV?$shared_object_ptr@VInputMessage@@@stdext@@@Z
> ```
> 
> **I think** it only happens in otclient (mehah and v8)
> 
> not testing enough on client old

Could you try another old but functional engine for version 860, and check that this doesn't happen in OTC as well?

Honestly, I just copied the code from the TFS 0.4 engine since it has always worked for many years and is still being used today. I don't know if you can check it, but if not, it's okay. I will review it when I have time.

**Comment by kokekanon** [comment]
repo      :  https://github.com/Fir3element/3777
Release :  The Forgotten Server 0.4  on Jul 3, 2022

Test 1 : +12 monster in stack  and 2 player work(Otcv8 and CipSoft ) : ✅

https://github.com/MillhioreBT/forgottenserver-downgrade/assets/114332266/63d63c8b-22f3-4838-a31d-4865179873c0

Test 2 :  12 Player in stack. work (Otcv8 and CipSoft ) ✅


https://github.com/MillhioreBT/forgottenserver-downgrade/assets/114332266/606acb2e-7a76-499d-bc5f-bd850a556a88

**Comment by MillhioreBT** [comment]
@kokekanon try test [beta-5](https://github.com/MillhioreBT/forgottenserver-downgrade/releases/tag/beta-test-5)

**Comment by kokekanon** [comment]
###  **Thanks, now works.**  @MillhioreBT 
I did these tests:

![jojos](https://github.com/MillhioreBT/forgottenserver-downgrade/assets/114332266/dcc6918b-d9b8-43b5-8b3d-a026b38c68ae)

OTCv8 ✅
CipSoft ✅

I'm going to keep testing, to make sure

**Comment by kokekanon** [comment]
[emil92b](https://otland.net/members/emil92b.189286/)  discovered an invisibility bug
![image](https://github.com/MillhioreBT/forgottenserver-downgrade/assets/114332266/1b6a8f33-a4a9-4318-8998-aaf8b4b363b8)

1. GM  say ./ghost
2. player up ladder o stack in teleport
3. gm stacks with the player. same sqm
4. bug
```
    [C++]: ?parseCreatureMove@ProtocolGame@@AEAAXAEBV?$shared_ptr@VInputMessage@@@std@@@Z
ERROR: no thing at pos:97 186 7, stackpos:255
at:
    [C++]: ?getMappedThing@ProtocolGame@@QEBA?AV?$shared_ptr@VThing@@@std@@AEBV?$shared_ptr@VInputMessage@@@3@@Z
ERROR: no creature found to move
at:
    [C++]: ?parseCreatureMove@ProtocolGame@@AEAAXAEBV?$shared_ptr@VInputMessage@@@std@@@Z
ERROR: no thing at pos:97 187 7, stackpos:255
at:
    [C++]: ?getMappedThing@ProtocolGame@@QEBA?AV?$shared_ptr@VThing@@@std@@AEBV?$shared_ptr@VInputMessage@@@3@@Z
ERROR: no creature found to move
at:
    [C++]: ?parseCreatureMove@ProtocolGame@@AEAAXAEBV?$shared_ptr@VInputMessage@@@std@@@Z
```


@MillhioreBT 


I think the bug is here
![image](https://github.com/MillhioreBT/forgottenserver-downgrade/assets/114332266/09cbd5ec-94f0-4210-9e04-27ccb8dcd910)

**Comment by kokekanon** [comment]
> perfect, thanks for testing these things, I'll check it and fix it

![image](https://github.com/MillhioreBT/forgottenserver-downgrade/assets/114332266/9343a82b-323d-4e99-b429-f7bd12c4b461)
creo que falto eso en ProtocolGame::sendMoveCreature

despues lo escribo en ingles jaja xd 
```
	if (!player->canSeeCreature(creature))
				return;
```
