### ISSUE TITLE
Server crashes due to NULL ptr

### ISSUE THREAD

**Issue by xmish** [MillhioreBT/forgottenserver-downgrade#6]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use contact.millhiorebt.com for support)
- [x] This issue is reproducible without changes to the C++ code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Login 1 GM
2. Login 1 Player
3. Walk a bit next to temple

### Actual behaviour

![image](https://github.com/MillhioreBT/forgottenserver-downgrade/assets/95135755/41b64feb-dab0-4bf1-8e0b-d095fbea040b)

`attacker` is NULL
https://github.com/MillhioreBT/forgottenserver-downgrade/blob/bac4f90e34465fce6b4e0b0efbd609ef527ffa8e/src/creature.cpp#L879

getCreatureByID() gives `nullptr` as owner is equal 0:
https://github.com/MillhioreBT/forgottenserver-downgrade/blob/bac4f90e34465fce6b4e0b0efbd609ef527ffa8e/src/condition.cpp#L1361

### Environment

Windows 10 Pro
22H2

**Comment by MillhioreBT** [comment]
> Aaa ok it's probably due to the condition that `player` has as `doDamage` does that for the player: healthChange = `-2`
> 
> ```
> {primary={type=COMBAT_EARTHDAMAGE (4) value=-2 } secondary={type=COMBAT_NONE (0) value=0 } origin=ORIGIN_CONDITION (1) ...}
>     primary: {type=COMBAT_EARTHDAMAGE (4) value=-2 }
>     secondary: {type=COMBAT_NONE (0) value=0 }
>     origin: ORIGIN_CONDITION (1)
>     blockType: BLOCK_NONE (0 '\0')
>     critical: false
>     leeched: false
> ```
> 
> Database condition to reproduce:
> 
> ```sql
> INSERT INTO mb.players (name,group_id,account_id,`level`,vocation,health,healthmax,experience,lookbody,lookfeet,lookhead,looklegs,looktype,lookaddons,direction,maglevel,mana,manamax,manaspent,soul,town_id,posx,posy,posz,conditions,cap,sex,lastlogin,lastip,save,skull,skulltime,lastlogout,blessings,onlinetime,deletion,balance,stamina,skill_fist,skill_fist_tries,skill_club,skill_club_tries,skill_sword,skill_sword_tries,skill_axe,skill_axe_tries,skill_dist,skill_dist_tries,skill_shielding,skill_shielding_tries,skill_fishing,skill_fishing_tries) VALUES
> 	 ('GM',6,2,1337,1,150,150,39654617600,0,0,0,0,136,0,1,0,0,0,0,0,1,95,128,7,0x,400,0,1685321026,16777343,1,0,0,1685321089,0,434,0,0,2520,10,0,10,0,10,0,10,0,10,0,10,0,10,0),
> 	 ('x',1,3,1337,1,96,150,39654617600,0,0,0,0,136,0,1,0,0,0,0,0,1,92,130,7,0x010004000002FFFFFFFF0360EA00001A001B000000001C00FE0101000000020000000003803801001A001B000000001C00080119000000000AD0070000FEFFFFFFA00F00000AA00F0000FEFFFFFFA00F00000AA00F0000FEFFFFFFA00F00000AA00F0000FFFFFFFFA00F00000AA00F0000FFFFFFFFA00F00000AA00F0000FFFFFFFFA00F00000AA00F0000FFFFFFFFA00F00000AA00F0000FFFFFFFFA00F00000AA00F0000FFFFFFFFA00F00000AA00F0000FFFFFFFFA00F00000AA00F0000FFFFFFFFA00F00000AA00F0000FFFFFFFFA00F00000AA00F0000FFFFFFFFA00F00000AA00F0000FFFFFFFFA00F00000AA00F0000FFFFFFFFA00F00000AA00F0000FFFFFFFFA00F00000AA00F0000FFFFFFFFA00F00000AA00F0000FFFFFFFFA00F00000AA00F0000FFFFFFFFA00F00000AA00F0000FFFFFFFFA00F0000FE,400,0,1685320921,16777343,1,0,0,1685321089,0,239,0,0,2520,10,0,10,0,10,0,10,0,10,0,10,0,10,0);
> ```
> 
> It's character with name `x`
> 
> Or even easier:
> 
> * get a player
> * spawn cobra and let it poison player
> * /kick player
> * relogin player
> * crash

Thanks for the report. I'll try it and fix it later.

**Comment by MillhioreBT** [comment]
![image](https://github.com/MillhioreBT/forgottenserver-downgrade/assets/28090948/a3eac980-a82d-4dcc-bc57-5fc3553e8cca)
[fixed.](https://github.com/MillhioreBT/forgottenserver-downgrade/commit/881ba5750dc0256bc72468193f17fd9b8cea56ff)

**Comment by MillhioreBT** [comment]
Could you not combine two problems in the same Issue?
it's confusing

**Comment by MillhioreBT** [comment]
The problem has already been fixed, if it still persists feel free to reopen the issue.
