### ISSUE TITLE
Issue with summon after master and summon are killed "at the same time"

### ISSUE THREAD

**Issue by luanluciano93** [MillhioreBT/forgottenserver-downgrade#7]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use contact.millhiorebt.com for support)
- [x] This issue is reproducible without changes to the C++ code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. I did the test in the task system by getting the task from the demons.
2. Then I went to orshaball and when he was summoned by a demon, I killed the master and the summon in the same spell hit.
3. This way, not always, but quite often, the demon summon is counted towards the task system.
**Note:** it was tested only by killing the demon, and it doesn't count as it has the "not master" check

### Reproduction environment
I made this video if you need to understand the problem: http://www.mediafire.com/file/ye6lsy8dk7rgd63/ProblemaMatandoSummon.mp4

**Comment by MillhioreBT** [comment]
A custom task system has nothing to do with this repository.

If it's a script you found on otland, please report it in that script's thread.

**Comment by luanluciano93** [comment]
Friend I'm not saying that the error is in the custom script, I said that in any case that you wanted to use only the master, this could be a problem.

`function onKill(player, target)
	if not player or not target or target:getMaster() then
		return true
	end`

**Comment by MillhioreBT** [comment]
> Friend I'm not saying that the error is in the custom script, I said that in any case that you wanted to use only the master, this could be a problem.
> 
> `if not player or not target or target:getMaster() then return true end`

Sorry for the delay in responding, I will review the case and do some tests, thank you for reporting this problem
